"""
Pydantic schemas for document ingestion.

This module defines the data models used for validating and processing
document JSON files during ingestion into the RAG system.

Note: document_id and chunk_id are NOT part of the input JSON schema.
They are auto-generated by the ingestion pipeline:
- document_id: Generated from file_name + created_date + title (SHA1 hash)
- chunk_id: Generated from document_id + page_number + chunk_index
"""

from typing import List, Dict, Any, Optional, Union
from pydantic import BaseModel, Field, field_validator


# Note: source_type is now flexible and accepts any string value
# No longer restricted to specific types for production robustness


class DocumentMetadata(BaseModel):
    """
    Metadata for a document being ingested.
    
    PRODUCTION-READY ROBUST METADATA SCHEMA:
    - Accepts NULL values in ALL fields (no defaults applied)
    - Accepts EMPTY STRINGS in all string fields
    - Accepts EMPTY LISTS in list fields
    - NO structural restrictions (dates, formats, etc.)
    - Maximum flexibility for real-world data
    
    This schema is designed to handle messy, incomplete, or inconsistent metadata
    from various sources without throwing validation errors. All validation is
    removed to ensure robustness in production environments.
    
    Note: The following fields are NOT part of the input JSON - they are auto-generated:
    - document_id: Generated from file_name + created_date + title (SHA1 hash)
    - ingestion_timestamp: Generated at ingestion time (ISO format)
    
    Attributes:
        title: Document title (accepts null, empty string, any value)
        path: Path to the original document file (accepts null, empty string, any value)
        author: Document author (accepts null, empty string, any value)
        created_date: Date the document was created (accepts null, empty string, any format)
        source_type: Type of source (accepts null, empty string, any value)
        language: Document language code (accepts null, empty string, any value)
        total_pages: Total number of pages (accepts null, any value - int or string)
        file_name: Original file name (accepts null, empty string, any value)
        tags: List of tags for categorization (accepts null, empty list, any values)
        extra_metadata: Additional metadata as key-value pairs (accepts null, empty dict, any values)
    """
    title: Optional[str] = Field(default=None, description="Document title (null, empty, or any string)")
    path: Optional[str] = Field(default=None, description="Path to the original document file (null, empty, or any string)")
    author: Optional[str] = Field(default=None, description="Document author (null, empty, or any string)")
    created_date: Optional[str] = Field(default=None, description="Date document was created (null, empty, or any format)")
    source_type: Optional[str] = Field(default=None, description="Source type (null, empty, or any string)")
    language: Optional[str] = Field(default=None, description="Document language code (null, empty, or any string)")
    total_pages: Optional[Union[int, str]] = Field(default=None, description="Total number of pages (null, int, or string)")
    file_name: Optional[str] = Field(default=None, description="Original file name (null, empty, or any string)")
    tags: Optional[List[Any]] = Field(default=None, description="Document tags (null, empty list, or list with any values)")
    extra_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional custom metadata (null, empty dict, or dict with any values including nulls)")


class ChunkInput(BaseModel):
    """
    A single chunk (paragraph) from a document.
    
    Note: chunk_id is NOT included here - it is auto-generated by the pipeline
    from document_id + page_number + chunk_index to ensure deterministic IDs.
    
    The summary field has been removed from the ingestion schema. If present in JSON,
    it will be ignored during validation.
    
    Attributes:
        page_number: Page number where chunk appears (1-indexed). Optional for audio files.
        chunk_index: Index of chunk within the page (1-indexed)
        paragraph_text: The actual text content of the chunk
        timestamp: Optional timestamp for audio files (e.g., "00:01:30")
    """
    model_config = {"extra": "ignore"}  # Ignore extra fields like 'summary'
    
    page_number: Optional[int] = Field(default=1, ge=1, description="Page number (1-indexed). Defaults to 1 for audio files.")
    chunk_index: int = Field(..., ge=1, description="Chunk index within page (1-indexed)")
    paragraph_text: str = Field(..., min_length=1, description="Exact paragraph text including captions and tables if any")
    timestamp: Optional[str] = Field(default=None, description="Timestamp for audio files (e.g., '00:01:30')")
    
    @field_validator('paragraph_text')
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate that text fields are non-empty after stripping whitespace."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty or whitespace-only")
        return v.strip()


class DocumentInput(BaseModel):
    """
    Complete document input for ingestion.
    
    PRODUCTION-READY ROBUST SCHEMA:
    - Metadata: FULLY FLEXIBLE - accepts null, empty strings, empty lists, any formats
    - Chunks: STRICT VALIDATION - ensures data quality for searchable content
    
    Expected JSON structure:
    
    {
        "document_metadata": {
            "title": "Document Title" | null | "",
            "path": "/path/to/document.pdf" | null | "",
            "author": "Author Name" | null | "",
            "created_date": "any format/structure" | null | "",
            "source_type": "any string" | null | "",
            "language": "en" | null | "",
            "total_pages": 120 | "120" | null,
            "file_name": "example.pdf" | null | "",
            "tags": ["tag1", "tag2"] | [] | null | [null, "", "valid"],
            "extra_metadata": {"key": "value", "nullable": null} | {} | null
        },
        "chunks": [
            {
                "page_number": 1,
                "chunk_index": 1,
                "paragraph_text": "Exact paragraph text..."
            }
        ]
    }
    
    METADATA FLEXIBILITY:
    - All fields accept null values (no defaults applied)
    - All string fields accept empty strings ""
    - Lists accept empty arrays []
    - No date format validation or structural restrictions
    - Maximum robustness for real-world messy data
    
    CHUNK VALIDATION:
    - Chunks require valid non-empty content for search quality
    - At least one chunk required per document
    - Summary field has been removed from the schema
    
    Note: The following are auto-generated by the pipeline (NOT part of input):
    - document_id: Generated from file_name + created_date + title
    - chunk_id: Generated from document_id + page_number + chunk_index
    - ingestion_timestamp: Generated at ingestion time
    
    Attributes:
        document_metadata: Metadata about the document (fully flexible, no restrictions)
        chunks: List of chunks (paragraphs) in the document (strict validation for quality)
    """
    document_metadata: DocumentMetadata = Field(..., description="Document metadata (accepts null, empty, any format)")
    chunks: List[ChunkInput] = Field(..., min_length=1, description="List of document chunks (requires valid content)")
    
    @field_validator('chunks')
    @classmethod
    def validate_chunks_non_empty(cls, v: List[ChunkInput]) -> List[ChunkInput]:
        """Validate that chunks list is non-empty."""
        if not v:
            raise ValueError("Document must contain at least one chunk")
        return v
