"""
Conversation Logger for Layered Graph RAG System.

Provides comprehensive logging of user-LLM-RAG interactions for debugging
and performance analysis. Logs all pipeline stages with timing information.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from datetime import datetime
import json
import os
from pathlib import Path


@dataclass
class ConversationLog:
    """
    Complete conversation log entry capturing all pipeline stages.
    
    This dataclass stores detailed information about each user query through
    the entire RAG pipeline, including:
    - User query and LLM-generated RAG command
    - All search results (vector, keyword, merged)
    - Reranking scores and anchor chunk selection
    - Graph traversal results (similar graph and probe graph)
    - Context expansion results
    - Final chunk selection and LLM response
    - Timing information for each stage
    - Error tracking
    """
    # Core identification
    timestamp: datetime
    session_id: str
    user_query: str
    
    # LLM Query Generation
    llm_generated_rag_command: Optional[Any] = None  # RAGCommand type
    
    # Search Results
    vector_search_results: List[Dict[str, Any]] = field(default_factory=list)
    keyword_search_results: List[Dict[str, Any]] = field(default_factory=list)
    merged_results: List[Dict[str, Any]] = field(default_factory=list)
    
    # Reranking
    reranking_scores: List[Dict[str, Any]] = field(default_factory=list)
    anchor_chunks: List[Dict[str, Any]] = field(default_factory=list)
    
    # Graph Traversal
    similar_graph_results: List[Dict[str, Any]] = field(default_factory=list)
    probe_graph_results: List[Dict[str, Any]] = field(default_factory=list)
    
    # Context Expansion
    context_expansion_results: List[Dict[str, Any]] = field(default_factory=list)
    
    # Final Results
    final_chunk_selection: List[Any] = field(default_factory=list)  # List[EnhancedChunkOutput]
    llm_response: str = ""
    
    # Final LLM call — full request and response for debugging
    llm_final_request: Optional[Dict[str, Any]] = None   # {system_prompt, user_query, chunks_sent}
    llm_final_response: str = ""                          # raw LLM output before cleaning
    
    # Performance Metrics
    total_processing_time: float = 0.0
    stage_timings: Dict[str, float] = field(default_factory=dict)
    
    # Error Tracking
    errors: List[str] = field(default_factory=list)
    
    # Resource Usage (optional)
    resource_usage: Dict[str, Any] = field(default_factory=dict)


class ConversationLogger:
    """
    Logs detailed conversation flow for debugging and analysis.
    
    Captures every stage of the user-LLM-RAG interaction pipeline:
    1. User query submission
    2. LLM-generated RAG command
    3. Vector and keyword search results
    4. Result merging and deduplication
    5. Reranking and anchor selection
    6. Graph traversal (similar and probe graphs)
    7. Context expansion
    8. Final chunk assembly
    9. LLM response generation
    10. Performance metrics and errors
    """
    
    def __init__(self, log_file_path: str = "logs/conversation_debug.jsonl"):
        """
        Initialize conversation logger.
        
        Args:
            log_file_path: Path to JSONL log file (default: logs/conversation_debug.jsonl)
        """
        self.log_file_path = log_file_path
        # Ensure log directory exists
        os.makedirs(os.path.dirname(log_file_path), exist_ok=True)
    
    def start_conversation(self, session_id: str, user_query: str) -> ConversationLog:
        """
        Initialize a new conversation log entry.
        
        Args:
            session_id: Unique session identifier
            user_query: Original user query
            
        Returns:
            New ConversationLog instance
        """
        return ConversationLog(
            timestamp=datetime.now(),
            session_id=session_id,
            user_query=user_query
        )
    
    def log_rag_command(self, log: ConversationLog, rag_command: Any) -> None:
        """
        Log the LLM-generated RAG command.
        
        Args:
            log: Conversation log instance
            rag_command: RAGCommand generated by LLM
        """
        log.llm_generated_rag_command = rag_command
    
    def log_search_results(
        self, 
        log: ConversationLog, 
        vector_results: List[Dict[str, Any]],
        keyword_results: List[Dict[str, Any]]
    ) -> None:
        """
        Log search results from vector and keyword searches.
        
        Args:
            log: Conversation log instance
            vector_results: Results from vector search
            keyword_results: Results from keyword search
        """
        log.vector_search_results = vector_results
        log.keyword_search_results = keyword_results
    
    def log_merged_results(
        self,
        log: ConversationLog,
        merged_results: List[Dict[str, Any]]
    ) -> None:
        """
        Log merged and deduplicated search results.
        
        Args:
            log: Conversation log instance
            merged_results: Merged results after deduplication
        """
        log.merged_results = merged_results
    
    def log_reranking(
        self, 
        log: ConversationLog, 
        all_chunks: List[Dict[str, Any]],
        reranked_results: List[Dict[str, Any]]
    ) -> None:
        """
        Log reranking process and scores.
        
        Args:
            log: Conversation log instance
            all_chunks: All chunks before reranking
            reranked_results: Top chunks after reranking (anchor chunks)
        """
        log.anchor_chunks = reranked_results
        
        # Extract reranking scores for analysis
        log.reranking_scores = [
            {
                "chunk_id": chunk.get("chunk_id"),
                "rerank_score": chunk.get("rerank_score", 0.0),
                "original_score": chunk.get("similarity_score", 0.0),
                "rank": idx + 1
            }
            for idx, chunk in enumerate(reranked_results)
        ]
    
    def log_graph_traversal(
        self,
        log: ConversationLog,
        similar_results: List[Dict[str, Any]],
        probe_results: List[Dict[str, Any]]
    ) -> None:
        """
        Log graph traversal results from both similar and probe graphs.
        
        Args:
            log: Conversation log instance
            similar_results: Results from similar graph traversal
            probe_results: Results from probe graph traversal
        """
        log.similar_graph_results = similar_results
        log.probe_graph_results = probe_results
    
    def log_context_expansion(
        self,
        log: ConversationLog,
        context_results: List[Dict[str, Any]]
    ) -> None:
        """
        Log context expansion results (adjacent chunks).
        
        Args:
            log: Conversation log instance
            context_results: Adjacent chunks added for context
        """
        log.context_expansion_results = context_results
    
    def log_llm_final_call(
        self,
        log: ConversationLog,
        system_prompt: str,
        user_query: str,
        chunks: List[Any],
        llm_raw_output: str
    ) -> None:
        """
        Log the complete data sent to the LLM for final answer generation,
        and the raw output it returned. Call this after the final stream completes.

        Args:
            log: Conversation log instance
            system_prompt: Full system prompt including all chunks
            user_query: Original user query sent as the user message
            chunks: List of EnhancedChunkOutput objects that were included
            llm_raw_output: Raw streamed output from the LLM before any cleaning
        """
        # Serialize chunks to a readable format
        serialized_chunks = []
        for chunk in chunks:
            if isinstance(chunk, dict):
                serialized_chunks.append({
                    "chunk_id": chunk.get("chunk_id", ""),
                    "document_path": chunk.get("document_path", ""),
                    "page_number": chunk.get("page_number", 0),
                    "origin": chunk.get("origin", ""),
                    "confidence": chunk.get("confidence", 0.0),
                    "text_preview": (chunk.get("text", "") or "")[:300],
                })
            else:
                serialized_chunks.append({
                    "chunk_id": getattr(chunk, "chunk_id", ""),
                    "document_path": getattr(chunk, "document_path", ""),
                    "page_number": getattr(chunk, "page_number", 0),
                    "origin": getattr(chunk, "origin", ""),
                    "confidence": getattr(chunk, "confidence", 0.0),
                    "text_preview": (getattr(chunk, "text", "") or "")[:300],
                })

        log.llm_final_request = {
            "system_prompt": system_prompt,
            "user_query": user_query,
            "chunks_count": len(serialized_chunks),
            "chunks": serialized_chunks,
        }
        log.llm_final_response = llm_raw_output

    def log_final_response(
        self,
        log: ConversationLog,
        final_chunks: List[Any],
        llm_response: str
    ) -> None:
        """
        Log final chunk selection and LLM response, then write to file.
        
        Args:
            log: Conversation log instance
            final_chunks: Final selected chunks (List[EnhancedChunkOutput])
            llm_response: Generated LLM response
        """
        log.final_chunk_selection = final_chunks
        log.llm_response = llm_response
        log.total_processing_time = (datetime.now() - log.timestamp).total_seconds()
        
        # Write complete log to file
        self._write_log(log)
    
    def log_error(self, log: ConversationLog, error_message: str) -> None:
        """
        Log an error that occurred during processing.
        
        Args:
            log: Conversation log instance
            error_message: Error description
        """
        log.errors.append({
            "timestamp": datetime.now().isoformat(),
            "message": error_message
        })
    
    def log_detailed_error(self, log: ConversationLog, error_details: Dict[str, Any]) -> None:
        """
        Log detailed error information with context and recovery recommendations.
        
        Args:
            log: Conversation log instance
            error_details: Detailed error information including context and recommendations
        """
        detailed_error = {
            "timestamp": datetime.now().isoformat(),
            "message": error_details.get("message", "Unknown error"),
            "context": error_details.get("context", {}),
            "recovery_recommendations": error_details.get("recovery_recommendations", []),
            "severity": error_details.get("context", {}).get("severity", "unknown"),
            "stage": error_details.get("context", {}).get("stage", "unknown"),
            "error_type": error_details.get("context", {}).get("error_type", "unknown")
        }
        
        log.errors.append(detailed_error)
    
    def log_stage_timing(self, log: ConversationLog, stage: str, duration: float) -> None:
        """
        Log timing information for a specific pipeline stage.
        
        Args:
            log: Conversation log instance
            stage: Stage name (e.g., "query_generation", "vector_search")
            duration: Duration in seconds
        """
        log.stage_timings[stage] = round(duration, 4)
    
    def log_resource_usage(
        self,
        log: ConversationLog,
        memory_mb: float,
        cpu_percent: float,
        active_connections: int
    ) -> None:
        """
        Log resource usage metrics.
        
        Args:
            log: Conversation log instance
            memory_mb: Memory usage in MB
            cpu_percent: CPU usage percentage
            active_connections: Number of active database connections
        """
        log.resource_usage = {
            "memory_mb": round(memory_mb, 2),
            "cpu_percent": round(cpu_percent, 2),
            "active_connections": active_connections,
            "timestamp": datetime.now().isoformat()
        }
    
    def _write_log(self, log: ConversationLog) -> None:
        """
        Write conversation log to JSONL file.
        
        Converts the ConversationLog dataclass to a JSON-serializable dictionary
        and appends it as a single line to the log file.
        
        Args:
            log: Conversation log instance to write
        """
        try:
            # Convert to serializable dict
            log_dict = {
                "timestamp": log.timestamp.isoformat(),
                "session_id": log.session_id,
                "user_query": log.user_query,
                
                # RAG Command
                "llm_generated_rag_command": self._serialize_rag_command(log.llm_generated_rag_command),
                
                # Search Results (counts and sample data)
                "vector_search_results_count": len(log.vector_search_results),
                "vector_search_sample": log.vector_search_results[:3] if log.vector_search_results else [],
                "keyword_search_results_count": len(log.keyword_search_results),
                "keyword_search_sample": log.keyword_search_results[:3] if log.keyword_search_results else [],
                "merged_results_count": len(log.merged_results),
                
                # Reranking
                "reranking_scores": log.reranking_scores,
                "anchor_chunks_count": len(log.anchor_chunks),
                "anchor_chunk_ids": [chunk.get("chunk_id") for chunk in log.anchor_chunks],
                
                # Graph Traversal
                "similar_graph_results_count": len(log.similar_graph_results),
                "probe_graph_results_count": len(log.probe_graph_results),
                "probe_graph_breakdown": self._get_probe_breakdown(log.probe_graph_results),
                
                # Context Expansion
                "context_expansion_results_count": len(log.context_expansion_results),
                
                # Final Results
                "final_chunk_selection_count": len(log.final_chunk_selection),
                "final_chunk_origins": self._get_chunk_origins(log.final_chunk_selection),
                "llm_response_length": len(log.llm_response),
                "llm_response_preview": log.llm_response[:200] if log.llm_response else "",
                
                # Full LLM final call (system prompt + chunks + user query + raw output)
                "llm_final_request": log.llm_final_request,
                "llm_final_response": log.llm_final_response,
                
                # Performance
                "total_processing_time": round(log.total_processing_time, 4),
                "stage_timings": log.stage_timings,
                
                # Errors and Resources
                "errors": log.errors,
                "resource_usage": log.resource_usage
            }
            
            # Write to JSONL file (one JSON object per line)
            with open(self.log_file_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_dict, default=str) + "\n")
                
        except Exception as e:
            # Fallback logging to stderr if file write fails
            print(f"ERROR: Failed to write conversation log: {e}", flush=True)
            print(f"Session ID: {log.session_id}, Query: {log.user_query[:100]}", flush=True)
    
    def _serialize_rag_command(self, rag_command: Any) -> Optional[Dict[str, Any]]:
        """Serialize RAG command to dict."""
        if rag_command is None:
            return None
        
        try:
            # Handle dataclass
            if hasattr(rag_command, '__dataclass_fields__'):
                return {
                    "vector_query": getattr(rag_command, 'vector_query', ''),
                    "keyword_query": getattr(rag_command, 'keyword_query', ''),
                    "probe_types": getattr(rag_command, 'probe_types', []),
                    "metadata_filter": getattr(rag_command, 'metadata_filter', None)
                }
            # Handle dict
            elif isinstance(rag_command, dict):
                return rag_command
            else:
                return str(rag_command)
        except Exception:
            return None
    
    def _get_probe_breakdown(self, probe_results: List[Dict[str, Any]]) -> Dict[str, int]:
        """Get breakdown of probe results by type."""
        breakdown = {}
        for result in probe_results:
            origin = result.get('origin', 'unknown')
            breakdown[origin] = breakdown.get(origin, 0) + 1
        return breakdown
    
    def _get_chunk_origins(self, chunks: List[Any]) -> Dict[str, int]:
        """Get breakdown of final chunks by origin."""
        origins = {}
        for chunk in chunks:
            # Handle both dict and dataclass
            if isinstance(chunk, dict):
                origin = chunk.get('origin', 'unknown')
            else:
                origin = getattr(chunk, 'origin', 'unknown')
            origins[origin] = origins.get(origin, 0) + 1
        return origins
    
    def get_log_file_path(self) -> str:
        """Get the current log file path."""
        return self.log_file_path
    
    def rotate_log_file(self, max_size_mb: int = 50) -> None:
        """
        Rotate log file if it exceeds max size.
        
        Args:
            max_size_mb: Maximum log file size in MB before rotation
        """
        try:
            if not os.path.exists(self.log_file_path):
                return
            
            file_size_mb = os.path.getsize(self.log_file_path) / (1024 * 1024)
            
            if file_size_mb > max_size_mb:
                # Rotate: rename current file with timestamp
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                base_path = Path(self.log_file_path)
                rotated_path = base_path.parent / f"{base_path.stem}_{timestamp}{base_path.suffix}"
                os.rename(self.log_file_path, rotated_path)
                
        except Exception as e:
            print(f"WARNING: Failed to rotate log file: {e}", flush=True)
